#pragma once
#include <iostream>
#include <vector>
#include <cmath>
#include "../../libs/MVS/Common.h"
#include "../../libs/MVS/Scene.h"

namespace MVS::ARKIT {

    static const std::string META_SUFFIX = "_metadata.json";
    static const std::string MASK_SUFFIX = "_mask.png";
    static const std::string DEPTHMAP_SUFFIX = "_depth.raw";
    static const std::string FEATURE_SUFFIX = "_feat.txt";

    // reference the score structure from scene.cpp#SelectNeighborViews#Score
   	struct Score {
        Score(): score(0.f), avgScale(0.f), avgAngle(0.f), points(0){}
		float score;
		float avgScale;
		float avgAngle;
		uint32_t points;
        std::vector<Point2f> pixels;
	};

    struct ARKITFrame {
        int index;
        std::string base_name;
        std::string image_name;
        std::string meta_name;
        std::string depthmap_name;

        ARKITFrame(int index, const std::string& base_name, const std::string& img, const std::string& meta, const std::string& depth)
            : index(index), base_name(base_name), image_name(img), meta_name(meta), depthmap_name(depth) {}     
    };

    struct ARKITScene {
        // the ownership of `scene` shall belong to OpenMVS codes, 
        // which should handle its construciton and serialization.        
        ARKITScene(Scene *scene): scene(scene), depthMapSize() {}

        // build Scene instance from ARKIT depthmaps,
        void build(const std::string& artkit_dir);

        // Return the interpolated depthmap wiht `newSize`
        cv::Mat getDepthMap(int index, const cv::Size& newSize = cv::Size());

        // Typical OpenmMVG + OpenMVS pipeline:
        // 1) OpenMVG generates a sparse point cloud where each point
        // associated with several images, determined through feature matching and bundle adjustment
        // 2) OpenMVS then uses these local releatinships to do the global selection that computing best neighboring views for each image.
        // ARKIT pipeline:
        // 1) ARKIT outputs depthmaps, skiping feature matching and BA
        // 2) Global selection is performed through visibility test using ARKIT depthmap
        void selectViews();

        // Select views for reference image with visibility, 
        // please refers to libs/MVS/SceneDensify.cpp#SelectViews for the detail rules
        void selectViews(Image& imageData, const std::vector<Camera>& cameras, const std::vector<cv::Mat>& depthMaps, float reprojectDepthError = 0.01);

        // The bridge between OpenMVS pipeline and ARKIT used to replace the global selection 
        bool selecViews(uint32_t imageID, DepthData& depthData);

        // The bridge between the OpenMVS pipeline and ARKit, used for depth initialization.
        // In OpenMVS's default implementation, depth maps and normal maps are initialized using 2D Delaunay triangulation.
        // Currently, we need to initialize depth maps using ARKit and compute normal vectors based on pixel and depth relationships.
        void initDepthMap(uint32_t imageID, DepthData& depthData);

        // Projects depth maps generated by ARKIT into a coarse point cloud,
        // witout any point cloud calibrations are performed.
        // This is only used to verify the correctness of coordinate transform from ARKIT to OpenMVS.
        void buildCoarsePointcloud(const std::string& ply_path);

        Camera loadCamera(int index, cv::Size newSize, bool transToRef = true);

        // Load arkit frames
        void load(const std::string& meta_json_path);

        // Serializes only arkit frames
        void save(const std::string& meta_json_path);

        Scene *scene;

        // arkit frames
        std::vector<ARKITFrame> arkitFrames;

        // raw depthmap size
        cv::Size depthMapSize;
    };

}